title: Luthfiyyah`s Journey
logo: /assets/img/https://thursd.com/storage/media/35810/Rose-Furiosa---De-Ruiter's-Red-Roses-for-Valentine's-Day-on-Thursd.jpeg 
description: Hello Everyone. Here, I will share my journey learn Data Science. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
